### PR TITLE
make keyframe foldable

### PR DESCRIPTION
**Pull request by xyc**
fixes https://github.com/codemirror/dev/issues/1223

https://github.com/codemirror/lang-css/assets/679275/63700493-b9a5-4a9d-a8a2-7e851bd64b51

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks!

**Comment by xyc** [comment]
Thank you! Any chance this would this be included in a new NPM release?

**Comment by marijnh** [comment]
Sure. I've tagged 6.2.1

**Comment by xyc** [comment]
thank you, appreciate the help!

**Pull request merged**
