### PR TITLE
Missing pseudo-classes

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
I have added missing pseudo-classes, that are supported by at least a single browser.

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
Should I add missing pseudo-elements here too or they should be made separate?

**Comment by marijnh** [comment]
Which pseudo-elements are those?

**Comment by NiedziolkaMichal** [comment]
[backdrop](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop), [cue](https://developer.mozilla.org/en-US/docs/Web/CSS/::cue), f[ile-selector-button](https://developer.mozilla.org/en-US/docs/Web/CSS/::file-selector-button), [marker](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker), [part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part), [slotted](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted), [target-text](https://developer.mozilla.org/en-US/docs/Web/CSS/::target-text). From those, part and slotted are accepting selector as their argument.

**Comment by marijnh** [comment]
Yes, I suppose those can also be added to that same list.

**Comment by NiedziolkaMichal** [comment]
Ok, I have added them to PR.

**Comment by marijnh** [comment]
Thanks!

**Pull request merged**
